version: "3.7"
services:
  mysql-dock:
    restart: always
    container_name: mysql-dock
    build:
      context: .
      dockerfile: mysql-docker/Dockerfile
    environment:
      MYSQL_DATABASE: social-network
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    volumes:
    - ./sql:/docker-entrypoint-initdb.d
    ports:
    - "6033:3306"

  social-network-app:
    restart: on-failure
    build:
      context: .
      dockerfile: social-network/Dockerfile
    environment:
      WAIT_HOST: mysql:3306
    depends_on:
      - mysql-dock
    ports:
      - "8080:8080"

#  mongo-dock:
#    restart: always
#    container_name: mongo-dock
#    image: mongo
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: root
#      MONGO_INITDB_DATABASE: social-network
#    ports:
#      - "27017:27017"
#
#  reminder-app:
#    restart: on-failure
#    build:
#      ./reminder-app/Dockerfile
#    depends_on:
#      - mongo-dock
#
#  activemq:
#    restart: always
#    image: rmohr/activemq
#    ports:
#      - "61616:61616"
#      - "8161:8161"