version: "3.7"
services:
  mysql-db:
    restart: always
    container_name: mysql-db
    build:
      context: .
      dockerfile: mysql-docker/Dockerfile
    environment:
      MYSQL_DATABASE: social-network
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    volumes:
    - ./sql:/docker-entrypoint-initdb.d
    ports:
    - "6033:3306"

  social-network-app:
    restart: on-failure
    container_name: social-network
    build:
      context: ./social-network
      dockerfile: Dockerfile
    depends_on:
      - mysql-db
    environment:
      WAIT_HOST: mysql-db:3306
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db/social-network?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    expose:
      - "8080"
    ports:
      - "8080:8080"

  mongo-db:
    restart: always
    container_name: mongo-db
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: social-network
    ports:
      - "27017:27017"

  reminder-app:
    restart: on-failure
    container_name: birthday-reminder
    build:
      context: ./reminder-app
      dockerfile: Dockerfile
    depends_on:
      - mongo-db
    environment:
      WAIT_HOST: mongo-db:27017
      SPRING_DATA_MONGODB_HOST: mongo-db
#      SPRING_DATA_MONGODB_PORT: 27017
#      SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE: admin
#      SPRING_DATA_MONGODB_URI: mongodb://mongo-db:27017
      SPRING_DATA_MONGODB_DATABASE: social-network
      SPRING_DATA_MONGODB_USERNAME: root
      SPRING_DATA_MONGODB_PASSWORD: root

#  activemq:
#    restart: always
#    image: rmohr/activemq
#    ports:
#      - "61616:61616"
#      - "8161:8161"